[package]
name = "lua_tools"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4.3.4", features = ["derive"]}


[[bin]]
name = "lua"

[[bin]]
name = "lua-dump"
